Fix: Add yc_zone to staging and production tfvars
ERROR: Illegal argument external_address_spec.zone_id || external_address_spec.region_id

ROOT CAUSE:
The yc_zone variable was null (default value in providers.tf)
VPC address resources require zone_id to be set
terraform.tfvars did not define yc_zone value

FIX:
- Add yc_zone = "ru-central1-b" to staging.tfvars
- Add yc_zone = "ru-central1-b" to production.tfvars

RESULT:
VPC address resources will now have valid zone_id
All 12 resources should be created successfully

RESOURCES TO CREATE:
- 4 x yandex_vpc_address (master + 3 workers)
- 2 x yandex_vpc_network (external + internal)
- 2 x yandex_vpc_subnet (external + internal)
- 4 x yandex_compute_instance (master + 3 workers)